### ISSUE TITLE
Request feature Query Data from Folder which Contain Many CSV Files ( ClickHouse  )

### ISSUE THREAD

**Issue by SoftTools59654** [l1xnan/DuckStudio#70]
Query Data from Folder which Contain Many CSV Files ( ClickHouse  )

To search for a specific text among multiple csv files

D:/Input/Files/*.csv

Thanks for the good software
I hope the new version will be released and the features you added. use

**Comment by l1xnan** [comment]
Query the CSV files in the Clickhouse? Clickhouse does not read local files and only uses duckdb.
